version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./web:/web
  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./app:/app
  db:
    build: ./mysql
    ports:
      - "33306:3306"
    restart: always
    environment:
        MYSQL_DATABASE: foosen
        MYSQL_ROOT_PASSWORD: password
